---
title: "Notebook_Coding_Consistency_Analysis"
author: "Lei Yue"
date: "2024-12-22"
output: html_document
---


# install packages
```{r}
rm(list = ls())

if (!require("pacman")) install.packages("pacman")

p_load("tidyverse" <- <- <- <- <- <- )
```


# load data
```{r}
## Chinese journals consistency data
load("Chin_Subj_check_data.Rdata")

## BTS consistency data
BTS_check_data <- readxl::read_xlsx("D://chin-subj//2_Data_Extraction//2_2_BTS//Chin_Subj_Proofreading_BTS_20250429.xlsx")
```


# Analysis
Chinese journals
```{r}
CE_score <- Chin_Subj_check_data %>% 
  dplyr::select(-c(1:2)) %>% 
  dplyr::mutate(across(everything(), ~as.numeric(as.character(.))),
                across(everything(), ~ifelse(. == 3, 3, 0)))

  # dplyr::summarise(across(everything(), ~mean(., na.rm = TRUE))) %>% 
  # tidyr::pivot_longer(cols = everything(), names_to = "Column_name", values_to = "Mean") %>%
  # mutate(Column_name = as.character(Column_name),
  #        Mean = round(Mean,4))

writexl::write_xlsx(CE_score,"CE_score.xlsx")
```


BTS
```{r}
BTS_CE_score <- BTS_check_data %>% 
  dplyr::filter(Coder == "check") %>% 
  dplyr::select(-c(1,4,10:11))
  
  
BTS_CE_score_range <- BTS_CE_score %>% 
   dplyr::mutate(across(everything(), ~as.numeric(as.character(.))),
                across(everything(), ~ifelse(. == 3, 3, 0)))

  # dplyr::summarise(across(everything(), ~mean(., na.rm = TRUE))) %>% 
  # tidyr::pivot_longer(cols = everything(), names_to = "Column_name", values_to = "Mean") %>%
  # mutate(Column_name = as.character(Column_name),
  #        Mean = round(Mean,4))

# write.csv(BTS_CE_score,"D://chin-subj//2_Data_Extraction//2_2_BTS//BTS_CE_score.csv",row.names = FALSE)

write.csv(BTS_CE_score_range,"D://chin-subj//2_Data_Extraction//2_2_BTS//BTS_CE_score2.csv",row.names = FALSE)
```


By the way, process BTS coding for the subsequent analysis
```{r}
BTS_coding <- BTS_check_data %>% 
  dplyr::filter(Coder == "final")

## Article_Id is not standardized
BTS_coding <- BTS_coding %>% 
  dplyr::mutate(Article_Id = ifelse(Article_Id == "Vlasceanuetal(2023)","Vlasceanu_et_al_2023",Article_Id),
                Article_Id = ifelse(Article_Id == "Kirklandetal(2022)","Kirkland_et_al_2022",Article_Id),
                Article_Id = ifelse(Article_Id == "Kelseyetal（2024）","Lucca_et_al_2024",Article_Id),
                Article_Id = ifelse(Article_Id == "Sorokowski（2020）","Sorokowski_et_al_2020",Article_Id),
                Article_Id = ifelse(Article_Id == "Anlloetal(2023)","Anllo_et_al_2023",Article_Id),
                Article_Id =ifelse(Article_Id == "Tyburetal(2016)","Tybur_et_al_2016",Article_Id),
                Article_Id = ifelse(Article_Id == "Bertoloetal(2023)","Bertolo_et_al_2023",Article_Id))

# There are two projects where there are two datasets respectively for adding rows to this.
## Azevedo_et_al_2022 and Klein_et_al_2018

BTS_coding <- BTS_coding %>% 
  dplyr::mutate(Article_Id = ifelse(Article_Id == "Azevedo_et_al_2022","Azevedo_et_al_2022_mainland",Article_Id),
                Article_Id =ifelse(Article_Id == "Klein_et_al_2018","Klein_et_al_2018_Slate1",Article_Id))

Add_row_data <- BTS_coding[c(3,16),] %>% 
  dplyr::mutate(Article_Id = ifelse(Article_Id == "Azevedo_et_al_2022_mainland","Azevedo_et_al_2022_taiwan",Article_Id),
                Article_Id =ifelse(Article_Id == "Klein_et_al_2018_Slate1","Klein_et_al_2018_Slate2",Article_Id))

## combine the two data
BTS_coding <-  bind_rows(BTS_coding,Add_row_data)

## Save Rdata
save(BTS_coding, file = "D://chin-subj//2_Data_Extraction//2_2_BTS//BTS_coding.Rdata")
```

