---
title: "Notebook_World_Population_Data_Process"
author: "Lei Yue"
date: "2025-07-04"
output: html_document
---


## Install packages
```{r}
rm(list = ls())

if (!require("pacman")) install.packages("pacman")

# use package "pacman" as loading R packages tools

pacman::p_load("tidyverse","openxlsx")
```


## Load data
```{r warning=FALSE}
## laod the Female's share of total population
WPP2024 <- read.csv("WPP2024.csv")

## load the world poopulation by single year
WPP2024_single_year <- read.csv("WPP2024_single_year.csv")
```


## Process data
```{r}
## total population and gener proportion
WPP2021_gender_prop <- WPP2024 %>% 
  dplyr::select(`Region..subregion..country.or.area..`,
                ISO3.Alpha.code,ISO2.Alpha.code,
                Type,Year,
                Total.Population..as.of.1.July..thousands.,
                Male.Population..as.of.1.July..thousands.,
                Female.Population..as.of.1.July..thousands.) %>% 
  dplyr::rename(Region = 1, ISO3 = 2, ISO2 = 3,
                Population = 6, Male_population = 7, Female_population = 8) %>% 
  dplyr::mutate(Male_proportion = Male_population / (Male_population + Female_population)*100,
                Female_proportion = Female_population / (Male_population + Female_population)*100)



## population by single year
WPP2021_single_year <- WPP2024_single_year %>% 
  dplyr::select(Region..subregion..country.or.area..,Type,Year,
                ISO3.Alpha.code,ISO2.Alpha.code,12:112) %>% 
  dplyr::rename(Region = 1, ISO3 = 4, ISO2 = 5) %>% 
  dplyr::mutate(Total_population = rowSums(across(X0:`X100.`)),
                `0-17` = rowSums(across(X0:X17))/Total_population*100,
                `18-25` = rowSums(across(X18:X25))/Total_population*100,
                `26-40` = rowSums(across(X26:X40))/Total_population*100,
                `41-59` = rowSums(across(X41:X59))/Total_population*100,
                `>=60` = rowSums(across(X60:`X100.`))/Total_population*100) %>% 
  dplyr::mutate(`0-10` = rowSums(across(X0:X10))/Total_population*100,
                `11-20` = rowSums(across(X11:X20))/Total_population*100,
                `21-30` = rowSums(across(X21:X30))/Total_population*100,
                `31-40` = rowSums(across(X31:X40))/Total_population*100,
                `41-50` = rowSums(across(X41:X50))/Total_population*100,
                `51-60` = rowSums(across(X51:X60))/Total_population*100,
                `>=61` = rowSums(across(X61:`X100.`))/Total_population*100)


## PsyStages
WPP2021_PsyStages <- WPP2021_single_year %>% 
  dplyr::select(Region,ISO3,ISO2,Type,Year,
                Total_population,
                `0-17`,`18-25`,`26-40`,`41-59`,`>=60`)

## interval10
WPP2021_interval10 <- WPP2021_single_year %>% 
  dplyr::select(Region,ISO3,ISO2,Type,Year,
                Total_population,
                `0-10`,`11-20`,`21-30`,`31-40`,`41-50`,`51-60`,`>=61`)
```


## Save Rdata
```{r}
save(WPP2021_gender_prop,WPP2021_PsyStages,WPP2021_interval10,
     file = "WPP2021_gender_age.Rdata")
```

